### ISSUE TITLE
nothing show

### ISSUE THREAD

**Issue by xiaokangkang6** [Rui-Chun/ESP32-CSI-Collection-and-Display#1]
Excuse me, could you please tell me why I have nothing to show here?
![8ac0f44ef6230d0deb71293aca25e77](https://user-images.githubusercontent.com/111182596/198220187-c35ab08f-23fe-46d3-afba-9f1a04982acb.jpg)

**Comment by Rui-Chun** [comment]
Please check the output of the ESP32 monitor mode. https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-monitor.html
There will be debugging info output.

**Comment by Rui-Chun** [comment]
Closing this issue.
